### ISSUE TITLE
Additionally, ensure that the device is not already connected, or alternatively, that it supports multiple connections.

### ISSUE THREAD

**Issue by HamzaSn** [TarlogicSecurity/BlueSpy#14]
What devices are affected with this issue ?

If a device is paired it's not vulnerable, and this attack is useless.
Because if it's not connected and you connect to some earbuds , well it's normal that you can record and play sound out of it
"or alternatively, that it supports multiple connections." is there any  ?

**Comment by jesusgomezmoreno** [comment]
The problem is that some earbuds don't notify the legitimate user when they're being paired with some other device, and this could cause an attacker to use the earbuds (and their microphone) without the knowledge of the user.

This is a PoC on how a vulnerable paring process could be exploited. It's part of a demonstration on how a failure to implement appropriate security in Bluetooth could impact the use of a device. You can find out more about this topic on our website: https://www.tarlogic.com/bsam/
